### ISSUE TITLE
Is this repo in a deployable state?

### ISSUE THREAD

**Issue by rdbartlett** [enspiral/whatis.enspiral.com#7]
@ahdinosaur can you confirm that the installation instructions in the readme are working? 

`npm run develop` is failing on my machine and I'm wondering if that is because I'm clueless about npm, or if the repo is in a broken state. If you can confirm the instructions, that will help with my troubleshooting :)

**Comment by ahdinosaur** [comment]
@rdbartlett i'm not aware of any reason why it shouldn't work. what error are you experiencing?

**Comment by ahdinosaur** [comment]
got an error using `node@6`, going back to `node@0.12` (what i used when i wrote this) works. recommend [`nvm`](https://github.com/creationix/nvm) for an easy way to handle multiple node versions. yet for some reason the styles are still wacky, hmm.

**Comment by rdbartlett** [comment]
Yep I got it working by switching to node 4.

The styles are wacky because master is currently in an intermediate state between the way you had it built with just graphics, to the version I got part-way through, which is html + css + translatable text. I can't remember what happened exactly, maybe I created a 'work in progress' pull request that wasn't clearly marked as such, and it got merged?

I think it would be good to revert it back to the state that you had it in (i.e. the version currently deployed on whatis.enspiral.com), and then I can create an issue with my ideal specs, and then look for a volunteer to implement it.

What do you think?

**Comment by ahdinosaur** [comment]
we did a series a pull requests back and forth which got us here. yep, can force push master back to the working state, and push the current master as a branch.

**Comment by ahdinosaur** [comment]
done, deployed is master and work in progress is [`i18n-html`](https://github.com/enspiral/whatis.enspiral.com/tree/i18n-html). look forward to an issue with your ideal specs and a volunteer to implement it. :smile:

**Comment by rdbartlett** [comment]
Cool! I don't see any changes on master though? Am I missing something or are you?

**Comment by ahdinosaur** [comment]
i did a force push on master (shhh...) moving the latest commit back to what is deployed. pushed what used to be master into [`i18n-html`](https://github.com/enspiral/whatis.enspiral.com/tree/i18n-html). does that make sense?

**Comment by rdbartlett** [comment]
Ohhhhh gotcha, my bad! 

Force push oh my gosh :P
